# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up maxim-lobanov/setup-xcode@v2
      with:
        xcode-version: '15.0'

    - name: Build and test
      run: |
        xcodebuild test -scheme YourSchemeName -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' -enableCodeCoverage YES
