# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos:
    strategy:
      matrix:
        xcode:
          - "15.1"

    name: macOS 14 (Xcode ${{ matrix.xcode }})
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make SwiftUtilsTests
